package UI;

/**
 *
 * @author Triệu Phan Thiên Bảo
 */
import DAO.NhanVienDAO;
import EntityClass.NhanVien;
import Utils.Auth;
import Utils.DateHelper;
import Utils.MsgBox;
import Utils.XImage;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.KeyEvent;
import java.io.File;
import java.util.*;
import javax.swing.*;
import javax.swing.table.*;
import java.sql.*;
import java.util.concurrent.TimeUnit;

public class ManageInformation extends javax.swing.JDialog {

    public ManageInformation(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setLocationRelativeTo(null);
        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_DiaChi = new javax.swing.JTextArea();
        lbl_DienThoai = new javax.swing.JLabel();
        txt_DienThoai = new javax.swing.JTextField();
        lbl_MatKhauHienTai = new javax.swing.JLabel();
        lbl_GioiTinh = new javax.swing.JLabel();
        lbl_MatKhauMoi = new javax.swing.JLabel();
        rad_Nam = new javax.swing.JRadioButton();
        txt_MatKhauHienTai = new javax.swing.JPasswordField();
        rad_Nu = new javax.swing.JRadioButton();
        txt_MatKhauMoi = new javax.swing.JPasswordField();
        pnl_Button = new javax.swing.JPanel();
        btn_Huy = new javax.swing.JButton();
        btn_CapNhat = new javax.swing.JButton();
        lbl_Image = new javax.swing.JLabel();
        lbl_TenDangNhap = new javax.swing.JLabel();
        lbl_NgaySinh = new javax.swing.JLabel();
        txt_TenDangNhap = new javax.swing.JTextField();
        dat_NgaySinh = new com.toedter.calendar.JDateChooser();
        chk_CapNhatMatKhau = new javax.swing.JCheckBox();
        lbl_HoTen = new javax.swing.JLabel();
        lbl_DiaChi = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        txt_CCCD = new javax.swing.JTextField();
        lbl_CCCD = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lbl_Anh = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txt_DiaChi.setColumns(10);
        txt_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_DiaChi.setRows(2);
        txt_DiaChi.setAutoscrolls(false);
        txt_DiaChi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DiaChiFocusLost(evt);
            }
        });
        jScrollPane2.setViewportView(txt_DiaChi);

        lbl_DienThoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DienThoai.setForeground(new java.awt.Color(0, 0, 153));
        lbl_DienThoai.setText("Điện thoại");

        txt_DienThoai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_DienThoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_DienThoaiFocusLost(evt);
            }
        });
        txt_DienThoai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_DienThoaiKeyTyped(evt);
            }
        });

        lbl_MatKhauHienTai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_MatKhauHienTai.setForeground(new java.awt.Color(0, 0, 153));
        lbl_MatKhauHienTai.setText("Mật khẩu hiện tại");

        lbl_GioiTinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_GioiTinh.setForeground(new java.awt.Color(0, 0, 153));
        lbl_GioiTinh.setText("Giới tính");

        lbl_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_MatKhauMoi.setForeground(new java.awt.Color(0, 0, 153));
        lbl_MatKhauMoi.setText("Mật khẩu mới");

        rad_Nam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_Nam.setForeground(new java.awt.Color(0, 0, 153));
        rad_Nam.setSelected(true);
        rad_Nam.setText("Nam");
        rad_Nam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
        });

        txt_MatKhauHienTai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_MatKhauHienTai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MatKhauHienTaiFocusLost(evt);
            }
        });
        txt_MatKhauHienTai.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MatKhauHienTaiKeyTyped(evt);
            }
        });

        rad_Nu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rad_Nu.setForeground(new java.awt.Color(0, 0, 153));
        rad_Nu.setText("Nữ");
        rad_Nu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
        });

        txt_MatKhauMoi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_MatKhauMoi.setEnabled(false);
        txt_MatKhauMoi.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_MatKhauMoiFocusLost(evt);
            }
        });
        txt_MatKhauMoi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_MatKhauMoiKeyTyped(evt);
            }
        });

        btn_Huy.setBackground(new java.awt.Color(153, 0, 0));
        btn_Huy.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_Huy.setForeground(new java.awt.Color(255, 255, 255));
        btn_Huy.setText("HUỶ");
        btn_Huy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_HuyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_HuyMouseExited(evt);
            }
        });
        btn_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HuyActionPerformed(evt);
            }
        });

        btn_CapNhat.setBackground(new java.awt.Color(51, 51, 255));
        btn_CapNhat.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        btn_CapNhat.setForeground(new java.awt.Color(255, 255, 255));
        btn_CapNhat.setText("CẬP NHẬT");
        btn_CapNhat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_CapNhatMouseExited(evt);
            }
        });
        btn_CapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CapNhatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_ButtonLayout = new javax.swing.GroupLayout(pnl_Button);
        pnl_Button.setLayout(pnl_ButtonLayout);
        pnl_ButtonLayout.setHorizontalGroup(
            pnl_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ButtonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_CapNhat, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_ButtonLayout.setVerticalGroup(
            pnl_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_ButtonLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_ButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                    .addComponent(btn_CapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbl_Image.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_Image.setForeground(new java.awt.Color(0, 0, 153));
        lbl_Image.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_Image.setText("Ảnh");

        lbl_TenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_TenDangNhap.setForeground(new java.awt.Color(0, 0, 153));
        lbl_TenDangNhap.setText("Tên đăng nhâp");

        lbl_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_NgaySinh.setForeground(new java.awt.Color(0, 0, 153));
        lbl_NgaySinh.setText("Ngày sinh");

        txt_TenDangNhap.setEditable(false);
        txt_TenDangNhap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        dat_NgaySinh.setDateFormatString("dd/MM/yyyy");
        dat_NgaySinh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dat_NgaySinh.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                dat_NgaySinhPropertyChange(evt);
            }
        });

        chk_CapNhatMatKhau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        chk_CapNhatMatKhau.setForeground(new java.awt.Color(0, 0, 153));
        chk_CapNhatMatKhau.setText("Cập nhật mật khẩu");
        chk_CapNhatMatKhau.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                chk_CapNhatMatKhauMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
        });
        chk_CapNhatMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_CapNhatMatKhauActionPerformed(evt);
            }
        });

        lbl_HoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_HoTen.setForeground(new java.awt.Color(0, 0, 153));
        lbl_HoTen.setText("Họ tên");

        lbl_DiaChi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_DiaChi.setForeground(new java.awt.Color(0, 0, 153));
        lbl_DiaChi.setText("Địa chỉ");

        txt_HoTen.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txt_CCCD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txt_CCCD.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_CCCDFocusLost(evt);
            }
        });

        lbl_CCCD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbl_CCCD.setForeground(new java.awt.Color(0, 0, 153));
        lbl_CCCD.setText("CCCD");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lbl_Anh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbl_AnhMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Anh, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_Anh, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnl_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lbl_GioiTinh)
                                    .addGap(214, 214, 214))
                                .addComponent(lbl_TenDangNhap, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(rad_Nam)
                                            .addGap(18, 18, 18)
                                            .addComponent(rad_Nu))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txt_DienThoai, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                                            .addComponent(txt_TenDangNhap)))
                                    .addComponent(lbl_HoTen)
                                    .addComponent(lbl_DienThoai)
                                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbl_NgaySinh)
                                    .addComponent(dat_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MatKhauHienTai)
                            .addComponent(lbl_MatKhauMoi)
                            .addComponent(chk_CapNhatMatKhau)
                            .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(99, 99, 99))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_MatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MatKhauHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_DienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_GioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rad_Nam)
                            .addComponent(rad_Nu)
                            .addComponent(chk_CapNhatMatKhau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dat_NgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_Image, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_TenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_CCCD, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Button, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_DiaChiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DiaChiFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_DiaChiFocusLost

    private void txt_DienThoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_DienThoaiFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_DienThoaiFocusLost

    private void txt_DienThoaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_DienThoaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (txt_DienThoai.getText().length() == 11 || !(Character.isDigit(c)) || c == KeyEvent.VK_DELETE || c == KeyEvent.VK_BACK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_DienThoaiKeyTyped

    private void txt_MatKhauHienTaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MatKhauHienTaiFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_MatKhauHienTaiFocusLost

    private void txt_MatKhauHienTaiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhauHienTaiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_MatKhauHienTaiKeyTyped

    private void txt_MatKhauMoiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_MatKhauMoiFocusLost
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_MatKhauMoiFocusLost

    private void txt_MatKhauMoiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_MatKhauMoiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (c == KeyEvent.VK_SPACE) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_MatKhauMoiKeyTyped

    private void btn_HuyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyMouseEntered
        // TODO add your handling code here:
        btn_Huy.setBackground(Color.yellow);
        btn_Huy.setCursor(new Cursor(Cursor.HAND_CURSOR));
        btn_Huy.setForeground(Color.blue);

    }//GEN-LAST:event_btn_HuyMouseEntered

    private void btn_HuyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_HuyMouseExited
        // TODO add your handling code here:
        btn_Huy.setBackground(new Color(153, 0, 0));
        btn_Huy.setForeground(Color.white);
    }//GEN-LAST:event_btn_HuyMouseExited

    private void btn_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HuyActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_HuyActionPerformed

    private void btn_CapNhatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseEntered
        // TODO add your handling code here:
        btn_CapNhat.setBackground(Color.yellow);
        btn_CapNhat.setForeground(Color.blue);
        btn_CapNhat.setCursor(new Cursor(Cursor.HAND_CURSOR));

    }//GEN-LAST:event_btn_CapNhatMouseEntered

    private void btn_CapNhatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_CapNhatMouseExited
        // TODO add your handling code here:
        btn_CapNhat.setBackground(new Color(51, 51, 255));
        btn_CapNhat.setForeground(Color.white);

    }//GEN-LAST:event_btn_CapNhatMouseExited

    private void btn_CapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CapNhatActionPerformed
//         TODO add your handling code here:/\
        capnhatNguoiDung();
    }//GEN-LAST:event_btn_CapNhatActionPerformed

    private void dat_NgaySinhPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_dat_NgaySinhPropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_dat_NgaySinhPropertyChange

    private void chk_CapNhatMatKhauMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_chk_CapNhatMatKhauMouseClicked
        // TODO add your handling code here:
        checkCapNhat();
    }//GEN-LAST:event_chk_CapNhatMatKhauMouseClicked

    private void txt_CCCDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_CCCDFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CCCDFocusLost

    private void lbl_AnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbl_AnhMouseClicked
        // TODO add your handling code here:
        this.chonAnh();
    }//GEN-LAST:event_lbl_AnhMouseClicked

    private void chk_CapNhatMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_CapNhatMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chk_CapNhatMatKhauActionPerformed

    private void MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MouseEntered
        // TODO add your handling code here:
        rad_Nam.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        rad_Nu.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        chk_CapNhatMatKhau.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
        lbl_Anh.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });

    }//GEN-LAST:event_MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ManageInformation dialog = new ManageInformation(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_CapNhat;
    private javax.swing.JButton btn_Huy;
    private javax.swing.JCheckBox chk_CapNhatMatKhau;
    private com.toedter.calendar.JDateChooser dat_NgaySinh;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_Anh;
    private javax.swing.JLabel lbl_CCCD;
    private javax.swing.JLabel lbl_DiaChi;
    private javax.swing.JLabel lbl_DienThoai;
    private javax.swing.JLabel lbl_GioiTinh;
    private javax.swing.JLabel lbl_HoTen;
    private javax.swing.JLabel lbl_Image;
    private javax.swing.JLabel lbl_MatKhauHienTai;
    private javax.swing.JLabel lbl_MatKhauMoi;
    private javax.swing.JLabel lbl_NgaySinh;
    private javax.swing.JLabel lbl_TenDangNhap;
    private javax.swing.JPanel pnl_Button;
    private javax.swing.JRadioButton rad_Nam;
    private javax.swing.JRadioButton rad_Nu;
    private javax.swing.JTextField txt_CCCD;
    private javax.swing.JTextArea txt_DiaChi;
    private javax.swing.JTextField txt_DienThoai;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JPasswordField txt_MatKhauHienTai;
    private javax.swing.JPasswordField txt_MatKhauMoi;
    private javax.swing.JTextField txt_TenDangNhap;
    // End of variables declaration//GEN-END:variables
    NhanVienDAO DAO = new NhanVienDAO();

    void init() {
        hienThongTin();
    }

    void hienThongTin() {
        txt_TenDangNhap.setText(Auth.user.getMaNV());
        txt_HoTen.setText(Auth.user.getTenNV());
        txt_DienThoai.setText(Auth.user.getSDT());
        if (Auth.user.getGioiTinh()) {
            rad_Nam.setSelected(true);
        } else {
            rad_Nu.setSelected(true);
        }
        dat_NgaySinh.setDate(Auth.user.getNgaySinhNV());
        txt_CCCD.setText(Auth.user.getCCCD());
        txt_DiaChi.setText(Auth.user.getDiaChi());
        if (Auth.user.getHinh() != null) {
            lbl_Anh.setToolTipText(Auth.user.getHinh());
            lbl_Anh.setIcon(XImage.readAvatars(Auth.user.getHinh()));
        }
    }

    void chonAnh() {
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            XImage.save(file);
            ImageIcon icon = XImage.readAvatars(file.getName());
            lbl_Anh.setIcon(icon);
            lbl_Anh.setToolTipText(file.getName());
        }
    }

    NhanVien getForm() {
        NhanVien nv = new NhanVien();
        nv.setMaNV(txt_TenDangNhap.getText());
        nv.setTenNV(txt_HoTen.getText());
        nv.setMatKhau(new String(txt_MatKhauHienTai.getPassword()));
        nv.setCCCD(txt_CCCD.getText());
        nv.setNgaySinhNV(dat_NgaySinh.getDate());
        nv.setDiaChi(txt_DiaChi.getText());
        nv.setSDT(txt_DienThoai.getText());
        nv.setGioiTinh(rad_Nam.isSelected());
        nv.setHinh(lbl_Anh.getToolTipText());
        return nv;
    }

    private void capnhatNguoiDung() {
        NhanVien nv = getForm();
        if (kiemLoi()) {
            if (chk_CapNhatMatKhau.isSelected()) {
                if (!checkMatKhauMoi()) {
                    MsgBox.alert(this, "Mật khẩu mới quá ngắn!!");
                    txt_MatKhauMoi.requestFocus();
                } else {
                    try {
                        DAO.update(nv);
                        hienThongTin();
                        MsgBox.alert(this, "Cập nhật thành công !!!");
                    } catch (Exception e) {
                        MsgBox.alert(this, "Cập nhật thất bại!! ");
                    }
                }
            } else {
                try {
                    DAO.update(nv);
                    hienThongTin();
                    MsgBox.alert(this, "Cập nhật thành công !!!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Cập nhật thất bại!! ");
                }
            }
        }

    }

    private void checkCapNhat() {
        if (chk_CapNhatMatKhau.isSelected()) {
            txt_MatKhauMoi.setEnabled(true);
        } else {
            txt_MatKhauMoi.setEnabled(false);
        }
    }

    boolean kiemLoi() {
        boolean ketqua = true;
        if (!checkCCCD()) {
            ketqua = false;
        }
        if (!checkDienThoai()) {
            ketqua = false;
        }
        if (!checkNgaySinh()) {
            ketqua = false;
        }
        if (!checkDiaChi()) {
            ketqua = false;
        }
        if (!checkMatKhau()) {
            ketqua = false;
        }
        return ketqua;
    }

    private boolean checkMatKhau() {
        String MatKhauHienTai = Auth.user.getMatKhau();
        if (txt_MatKhauHienTai.getPassword().length >= 3) {
            if (MatKhauHienTai.equals(new String(txt_MatKhauHienTai.getPassword()))) {
                return true;
            } else {
                MsgBox.alert(this, "Sai MK");

                return false;
            }
        } else {
            MsgBox.alert(this, "Sai MK");

            return false;
        }
    }

    boolean checkMatKhauMoi() {
        if (new String(txt_MatKhauMoi.getPassword()).length() >= 3) {
            return true;
        } else {
            return false;
        }
    }

    boolean checkNgaySinh() {
        if (dat_NgaySinh.getDate() != null) {
            java.util.Date NgayHienTai = DateHelper.now();
            java.util.Date NgaySinh = dat_NgaySinh.getDate();
            long kiemtra = DateHelper.getDateDiff(NgaySinh, NgayHienTai, TimeUnit.DAYS);
            if (kiemtra / 365 < 18) {
                MsgBox.alert(this, "Tuổi nhân viên phải từ 18 trở lên");
                return false;
            }
        }
        return true;
    }

    boolean checkDienThoai() {
        if (txt_DienThoai.getText().length() < 10 || txt_DienThoai.getText().length() > 11) {
            MsgBox.alert(this, "Sai SDT");
            return false;
        } else {
            return true;
        }
    }

    boolean checkDiaChi() {
        if (txt_DiaChi.getText().isEmpty()) {
            MsgBox.alert(this, "Sai Địa Chỉ");
            return false;
        } else {
            return true;
        }
    }

    boolean checkCCCD() {
        if (txt_CCCD.getText().length() < 12 || txt_CCCD.getText().length() > 12) {
            MsgBox.alert(this, "Sai CCCD");
            return false;
        } else {
            return true;
        }
    }
}
